<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_company_name</name>
   <tag></tag>
   <elementGuidId>8e35ab50-ac19-4d81-9640-898b23c84647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='company_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;company_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aace1959-dd6d-4814-a557-2f46f7e4e180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28901797-01c3-454e-bb5c-6b2c325fc346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_name</value>
      <webElementGuid>325b0258-18c9-4692-a766-e0b1718aa86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company name</value>
      <webElementGuid>45ba50f6-8eb8-4b56-8f2a-e84e9abf62f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/fieldset[1]/div[@class=&quot;pure-control-group&quot;]/input[1]</value>
      <webElementGuid>b4f640fc-0059-46e4-b927-c6dbe0ba2706</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='company_name']</value>
      <webElementGuid>4826195b-4ba5-4982-b06c-987d18c6fbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='main']/fieldset/div[2]/input</value>
      <webElementGuid>7924aea3-1ade-4de7-a857-28b659de156e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e0002e59-3452-43d9-a2c5-47af080b1d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'company_name' and @placeholder = 'Company name']</value>
      <webElementGuid>cf8056ba-be91-463d-9a19-8ca1be3e578b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
