<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Category Name</name>
   <tag></tag>
   <elementGuidId>b9eb34c2-accf-4fe1-87ce-e4ce426b0657</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='p_name0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#p_name0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec0f7cf3-a6f7-448a-8549-4b9f1b6076b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>875d3ff9-f3e7-436f-97f6-8acf46a33cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p_name0</value>
      <webElementGuid>7bd4859a-d622-43b8-aa56-8bf96b9e826c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name[0]</value>
      <webElementGuid>60574a63-72ea-4e92-8cc4-4ad5ee09d54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-width</value>
      <webElementGuid>88c254e6-f632-4af5-ab03-28d7b558fa26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p_name0&quot;)</value>
      <webElementGuid>cb8fe109-d2ed-4b5e-b637-1c8bed024a47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='p_name0']</value>
      <webElementGuid>f88d3f54-d912-4fc1-be8e-946d1108427f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='save-form']/div/div/input</value>
      <webElementGuid>a1e15ed9-4dfc-4c54-9f54-a19114a5b1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>01b529fc-616f-4877-9f67-4cf56e933047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'p_name0' and @name = 'name[0]']</value>
      <webElementGuid>c99263ab-5a7c-45b6-8345-2725caad4664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
