<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK_delete</name>
   <tag></tag>
   <elementGuidId>d67389b1-dfd1-40b9-89fc-fa3b63fe6705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ajs-button.ajs-ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you want to delete selected items?'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'OK' or . = 'OK')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d54fe81a-f1d3-4129-b42a-61e2b8a8aafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajs-button ajs-ok</value>
      <webElementGuid>dd2ac893-12c9-4bb2-82f8-a8cae04d96d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>5ce781cd-0b0c-4890-afba-6d5af6368cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;purecss ajs-no-overflow&quot;]/div[@class=&quot;alertify  ajs-movable ajs-closable ajs-pinnable ajs-fade ajs-maximizable&quot;]/div[@class=&quot;ajs-modal&quot;]/div[@class=&quot;ajs-dialog&quot;]/div[@class=&quot;ajs-footer&quot;]/div[@class=&quot;ajs-primary ajs-buttons&quot;]/button[@class=&quot;ajs-button ajs-ok&quot;]</value>
      <webElementGuid>1f346471-bc39-44f7-aa49-c36471e26f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you want to delete selected items?'])[1]/following::button[1]</value>
      <webElementGuid>9b051771-682c-4f53-b4a2-123e86446e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete selected item'])[1]/following::button[1]</value>
      <webElementGuid>1c1954cf-76e2-4a61-9db8-5aa50d68112b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::button[1]</value>
      <webElementGuid>a95443f5-0856-453a-b3cd-2671c59325cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>0dc9113a-6bd9-401d-858c-3892b4093614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>00761d03-df30-4a3a-8d9d-4c24e7eaa380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>ca532c50-bd6f-461e-92df-c25fcbf9fd5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
