<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_pid-13</name>
   <tag></tag>
   <elementGuidId>07b8f660-dcf0-472f-85c5-cef1c087690e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pid-13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pid-13']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'checkbox' and @value = '${number}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c3142e8-9413-4e6b-b812-3af8b319aeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pid-13</value>
      <webElementGuid>91eb9a9a-ba82-4b3d-9e9e-c154093b294a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3b45af95-451b-4e7e-9fd6-496657d812a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${number}</value>
      <webElementGuid>0a559b44-9260-42d1-8010-ab68445b7991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item_checkbox</value>
      <webElementGuid>bdbf1ac8-84eb-4694-b5c3-72e454b60ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pid-13&quot;)</value>
      <webElementGuid>b8e9020f-e9a3-4427-815a-33d74cc17260</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pid-13']</value>
      <webElementGuid>6bfc8c1d-14cf-48c2-aef5-d8d2c059ca97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-products']/table/tbody/tr/td/input</value>
      <webElementGuid>5d75f14a-039e-44da-9678-77258d56e35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>b9a3783c-0af7-46c2-93f7-09d43c91d522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pid-13' and @type = 'checkbox']</value>
      <webElementGuid>b20bbb90-be9d-40f9-a4ab-9c9a77989517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
